<?php
use Magento\Framework\View\Element\Template;

/** @var $block Template */
?>

<ul class="top_links top_links_left">
    <li class="top_links__link">
        <a href="#">
            <i class="dnd-pin"></i>
            Nos boutiques
        </a>
    </li>
    <li class="top_links__link">
        <a href="#">
            <i class="dnd-message"></i>
            Prendre rendez-vous
        </a>
    </li>
</ul>

<?= $block->getChildHtml('minicart'); ?>

