<?php
// Footer top for site links

use Magento\Framework\View\Element\Template;

/** @var $block Template */
?>
<div class="footer content footer-navigation">
    <img src="<?php echo $this->getViewFileUrl('images/logotype_white.svg'); ?>" alt="DN'D">

    <div class="footer-links-container">
        <article>
            <h3>
                Dn'D Brand Dn'D Watches
            </h3>
            <ul class="footer links">
                <li class="nav item">
                    <a href="#">Qui sommes-nous ?</a>
                </li>
                <li class="nav item">
                    <a href="#">Nos engagements</a>
                </li>
                <li class="nav item">
                    <a href="#">Nos conseils</a>
                </li>
                <li class="nav item">
                    <a href="#">Rolex</a>
                </li>
            </ul>
            <ul class="footer links">
                <li class="nav item">
                    <a href="#">Nos services</a>
                </li>
                <li class="nav item">
                    <a href="#">Nous rejoindre</a>
                </li>
                <li class="nav item">
                    <a href="#">Actualités boutique</a>
                </li>
            </ul>
        </article>
        <article>
            <h3>
                Aide
            </h3>
            <ul class="footer links">
                <li class="nav item">
                    <a href="#">FAQ</a>
                </li>
                <li class="nav item">
                    <a href="#">Livraison</a>
                </li>
                <li class="nav item">
                    <a href="#">Trouver une boutique</a>
                </li>
            </ul>
            <ul class="footer links">
                <li class="nav item">
                    <a href="#">E-réservation</a>
                </li>
                <li class="nav item">
                    <a href="#">Retours / Remboursement</a>
                </li>
                <li class="nav item">
                    <a href="#">*Conditions des offres</a>
                </li>
            </ul>
        </article>
    </div>

</div>
